//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practica1._3
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIRECTOR
    {
        public int ID_Director { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Country_ID { get; set; }
    
        public virtual COUNTRY COUNTRY { get; set; }
    }
}
